server:
  port: 8082
  servlet:
    context-path: /marais-event-push

logging:
  level:
    ROOT: INFO


spring:
#  kafka:
#    bootstrap-servers: "localhost:9092"
#    consumer:
#      group-id: spinGroup
  kafka:
    bootstrap-servers: dev.marais-stage.com:9092
    consumer:
      group-id: spinGroup
      bootstrap-servers: dev.marais-stage.com:9092
      auto-offset-reset: earliest
    producer:
      group-id: spinGroup
      bootstrap-servers: dev.marais-stage.com:9092
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

kafka:
  input:
    topic: spin-input
  output:
    topic: spin-output
  event-push:
    topic: event-push

stomp:
  topic: /topic/greeting
  event-push-topic: "/topic/event-push/%s"